### ISSUE TITLE
entrypoint.sh is visible to world

### ISSUE THREAD

**Issue by MarkErik** [martialblog/docker-limesurvey#101]
I noticed that I can view the entrypoint.sh and other files (e.g. composer.json, phpunit.xml...etc) that are in the root directory of my LimeSurvey installation via a web browser.

Is that a configuration problem with my installation, or is that how it behaves for other people as well?

If it *isn't* a problem with my install, then is this ideal behaviour to allow those files to be viewed? It seems like people shouldn't be able to poke around our configuration files.

**Comment by martialblog** [comment]
Hi, 

depends on you configuration and how you run the Image. 

the actual configuration (i.e. config.php) should and is not readable if you are using the provided Apache Image. This is true for all PHP files:

```
curl -I http://localhost:8080/application/config/config.php
HTTP/1.1 403 Forbidden
```

As for other text files, yes they are readable in the default settings.

```
curl -I http://localhost:8081/phpunit.xml
HTTP/1.1 200 OK

curl -I http://localhost:8081/entrypoint.sh
HTTP/1.1 200 OK
```

Both of which are public anyways (i.e. via GitHub) so there's no risk there. However, I can see how someone might want to restrict that. 

What is always possible is to inject another Apache configuration that changes this behaviour.

**Comment by martialblog** [comment]
@jacksgt What do you think, fiddle around in the apache.conf to be more restrictive? I'm on the fence about that...

**Comment by MarkErik** [comment]
At the risk of side-tracking the conversation a bit, looking at the nginx.conf example, it seems like application/config/config.php isn't restricted from view. (I could be wrong though in my reading of the .conf file)

**Comment by martialblog** [comment]
Sure we can add that to the example config. Even simpler:

```
- location ~ ^/(protected|framework|themes/\w+/views) {
+ location ~ ^/(protected|application|framework|themes/\w+/views) {
```

**Comment by jacksgt** [comment]
Why is the `entrypoint.sh` in `/var/www/html` in the first place?
I guess it's there for historical reasons... but IMO that's a bit strange.
`/entrypoint.sh` or `/usr/local/bin/entrypoint.sh` would make more sense.

**Comment by martialblog** [comment]
Yeah that makes sense. See that is why I value your input so much!

**Comment by jacksgt** [comment]
@MarkErik Thanks for raising this issue!

> I ran the example project, with fpm alpine and nginx, and trying to access /application/config/config.php comes back with a "no direct script access allowed" - I'm not sure whether this is better than denying and returning a 404 via adding lines into the nginx.conf since this is a very sensitive file e.g.

I agree that these files are sensitive. As far as I know, basically all PHP projects (Limesurvey, Nextcloud etc.) use this mechanism (`no direct script access allowed`) to "protect" their configuration files.
Even if you could access the `config.php`, you still wouldn't be able to extract any secrets because the PHP gets evaluated on the server-side and only the result is sent to the client (i.e. whatever the script `prints`).

Thus, I don't think it's necessary to add an extra protection mechanism here.
However, the files might be readable by a client when you `cp config.php config.php.bak` (*I haven't verified this*).

https://github.com/martialblog/docker-limesurvey/blob/master/examples/nginx.conf#L28

**Comment by martialblog** [comment]
Ok yeah creating non-PHP files is a bad idea

```
curl http://localhost:8080/application/config/config.php.backup

<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
return array(
  'components' => array(
    'db' => array(
      'connectionString' => 'mysql:host=lime-db;port=3306;dbname=limesurvey;',
```

I extended the example configuration in #103

**Comment by martialblog** [comment]
@MarkErik I just merged two related PRs. One updates the example nginx.conf the other moves the entrypoint to directory that is not served by the webserver.

**Comment by martialblog** [comment]
With the new tags, this is now in the latest Images
