### ISSUE TITLE
How to setup limesurvey on a sub-path

### ISSUE THREAD

**Issue by SebastianCmentowski** [martialblog/docker-limesurvey#106]
I am trying to setup this limesurvey container on a custom path prefix (eg /limesurvey) using Traefik.
However, I just can't get it working.
If I split the prefix, the pages loads, but limesurvey's automatic forwarding (from index.php/admin to the login page) misses the necessary prefix.
If I keep the prefix, limesurvey does not work properly anymore (due to not finding the own ressources).

Any idea how I could get it working?

**Comment by martialblog** [comment]
Hi, what Image/Configuration are you using?

If it's the Apache Image, could be that you need to adjust the `apache.conf` and or `BASE_URL`. 

https://github.com/martialblog/docker-limesurvey/blob/master/examples/apache-example.conf

Might be related to #49

**Comment by SebastianCmentowski** [comment]
I tried various configurations (apache, external nginx server...).
Tbh, I don't have much expertise in configuring webservers and never worked with Apache before.
I tried changing the configuration (mounting the changed file into the container like this: - ${PWD}/000-default.conf:/etc/apache2/sites-available/000-default.conf), but as Apache still mocks about not knowing the ServerName, I reckon that the config is not even active

**Comment by jacksgt** [comment]
This is definitely something we should document. 

@SebastianCmentowski Please share the Traefik configuration you are using and which environment you are in (docker compose, kubernetes etc.)

If I understand the Apache configuration in this repository correctly, the only thing you need to set for limesurvey if the BASE_URL environment variable, e.g. `BASE_URL=https://example.com/limesurvey/`.

**Comment by SebastianCmentowski** [comment]
Hi @jacksgt,

sure, here you go:
[docker-compose.txt](https://github.com/martialblog/docker-limesurvey/files/7609841/docker-compose.txt) (I attached the complete docker-compose as txt - yml not supported) 

My whole setup is based on docker-compose, with Traefik running alongside Portainer and GitLab (all of them already isolated by path prefixes).

**Comment by martialblog** [comment]
Once we got this figured out, we shoud put a working example in the repository.

**Comment by martialblog** [comment]
I started drawing up an example with Traefik and a Path. However, with the present config we run into the issue with the Admin URL. Meaning when entering a password you will get redirected to the wrong path.

https://github.com/martialblog/docker-limesurvey/blob/traefik-example/docker-compose.traefik.yml

**Comment by martialblog** [comment]
Ok so the StripPrefix won't work, you have to pass an Alias config in the webserver.

See https://github.com/martialblog/docker-limesurvey/pull/108

**Comment by SebastianCmentowski** [comment]
I just tried the solution and it works perfectly fine! Thanks a lot!
