### ISSUE TITLE
error 500 when try to access responses after upgrade

### ISSUE THREAD

**Issue by rafaelmr2** [martialblog/docker-limesurvey#111]
Hi, I'm using LimeSurvey 5.2.4. When I try to access responses of past surveys (on new after upgrade it's ok) I receive a error 500 (in web don't complete requisition, stay in loop). In log the error below:
```
limesurvey-php | 192.168.16.4 -  07/Dec/2021:17:02:01 -0300 "GET /index.php" 500
limesurvey-web | 172.31.0.2 - - [07/Dec/2021:17:02:01 -0300] "GET /index.php/responses/browse?surveyId=741679&1638907321155 HTTP/1.1" 500 2685 "https://rj.pcb.org.br/index.php/surveyAdministration/rendersidemenulink?surveyid=741679&subaction=plugins" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
```
I enabled in `application/config/config.php`:
```
'debug'=>2,
'debugsql'=>2,
```
But only shows this lines above and anymore.
Thanks.

**Comment by rafaelmr2** [comment]
Now I had this error:
```
500: Erro interno do servidor
Wrong decryption key! Decryption key has changed since this data were last saved, so data can't be decrypted. Please consult our manual at https://manual.limesurvey.org/Data_encryption#Errors.
```
But I use variables on docker-compose:

```
ENCRYPT_KEYPAIR: xxxx
ENCRYPT_PUBLIC_KEY: xxx
ENCRYPT_SECRET_KEY: xxxx
```

**Comment by martialblog** [comment]
Could this be related to https://github.com/martialblog/docker-limesurvey/pull/99 ?

Unfortunately the LS Documentation is not the best when it comes to the encryption

**Comment by rafaelmr2** [comment]
Hi,
I discovered that I didn't set this vars when I upgrade to version 5:

ENCRYPT_NONCE | Data encryption nonce (used in 5.0)
ENCRYPT_SECRET_BOX_KEY | Data encryption secret box key (used in 5.0)

I recovered from a backup and I can access now.

Thanks and sorry about that!

**Comment by martialblog** [comment]
No worries. Maybe I'll open an issue at LS to updated their documentation
