### ISSUE TITLE
Docker install using "latest" tag installs 4.x version of Limesurvey

### ISSUE THREAD

**Issue by gregwbrooks** [martialblog/docker-limesurvey#114]
Title says it all. Using Docker Compose with martialblog/docker-limesurvey:latest creates a working container with an older version of Limesurvey. Probably a minor thing, but I couldn't figure out how to fix it.

**Comment by martialblog** [comment]
Thanks for the hint, we must have overlook that when migrating the autobuild to GitHub.

**Comment by martialblog** [comment]
@jacksgt  I think we can just change this to `true` and that should do the trick

https://github.com/martialblog/docker-limesurvey/blob/master/.github/workflows/build-latest-container-images.yaml#L55

**Comment by jacksgt** [comment]
Sure, we can change that.
But wasn't there some agreement about not publishing `latest` tags at the time?

**Comment by martialblog** [comment]
Hm yeah I think so... people should be encouraged not to use it in prod. But I guess it's convenient.

**Comment by martialblog** [comment]
I think this was the discussion https://github.com/martialblog/docker-limesurvey/issues/26
