### ISSUE TITLE
SIGWINCH on docker-compose up

### ISSUE THREAD

**Issue by omerfarukz** [martialblog/docker-limesurvey#118]
Tried to run on windows with linux(lcow) kernel. Simply cloned repo and call "docker-compose up". Errors are below.

`Step 1/20 : FROM php:8.0-apache
 ---> 55ce1043ee12
Step 2/20 : LABEL maintainer="markus@martialblog.de"
1 error occurred:
        * Status: Invalid signal: SIGWINCH, Code: 1`

**Comment by martialblog** [comment]
Hey, this might be more of an Apache/Windows issue. I don't know if I can help with that
