### ISSUE TITLE
Traefik example not working

### ISSUE THREAD

**Issue by marodriguezr** [martialblog/docker-limesurvey#132]
Hi, first of all I'd like to thank all the maintainers for such great work.

I've noticed that the traefik example at first sight works well, but when I try to access other routes such as /limesurvey/admin, the application does nothing, for instance only the index page is accessible. 
I'd like to add that I also tried this with caddy's reverse proxy directive but the problem persists.

Thanks for reading, I'd really appreciate any insight on setting limesurvey under a subdirectory.

**Comment by martialblog** [comment]
Hi, thanks for the feedback. 

Unfortunately that is a known issue and I don't really have a solution yet. I don't think that is a Container related issue and should also occur when using a direct installation of the app. Maybe we can ask in the official LimeSurvey forum.

These issues are related:
- https://github.com/martialblog/docker-limesurvey/issues/49
- https://github.com/martialblog/docker-limesurvey/issues/106
- https://github.com/martialblog/docker-limesurvey/issues/127

**Comment by martialblog** [comment]
I updated the examles, they should work out-of-the-box. Let me know if there are any more issues.
