### ISSUE TITLE
Missing linux/amd64 images for latest 5.x releases

### ISSUE THREAD

**Issue by edgarrmondragon** [martialblog/docker-limesurvey#149]
Hi!

I noticed the missing images after seeing this error in a pipeline: `no matching manifest for linux/amd64 in the manifest list entries`.

<img width="1254" alt="Screenshot 2023-04-20 at 16 20 40" src="https://user-images.githubusercontent.com/16805946/233499440-7ae0b8b5-428a-4d2a-bbb9-20352786011d.png">

**Comment by martialblog** [comment]
Thanks for the hint, I'll fix it.

**Comment by martialblog** [comment]
New builds are on their ways... those new ARM builds take a while.
