### ISSUE TITLE
Add support for passwords in files

### ISSUE THREAD

**Issue by kdomke** [martialblog/docker-limesurvey#154]
If you deploy the image in a swarm environment the only secure way of providing passwords is via docker secrets.

```
echo SuperSecurePassword | docker secrets create secret_password
```

Those secrets are presented to the container via virtual files. 

With many other images there is a file based alternative to supply the password, [mariadb ](https://hub.docker.com/_/mariadb) e.g.
```
MARIADB_ROOT_PASSWORD_FILE=/run/secret/secret_password
```

The implementation in the [entrypoint.sh ](https://github.com/MariaDB/mariadb-docker/blob/master/11.2/docker-entrypoint.sh) does not look too bad (lines 22ff):
```
# usage: file_env VAR [DEFAULT]
#    ie: file_env 'XYZ_DB_PASSWORD' 'example'
# (will allow for "$XYZ_DB_PASSWORD_FILE" to fill in the value of
#  "$XYZ_DB_PASSWORD" from a file, especially for Docker's secrets feature)
file_env() {
	local var="$1"
	local fileVar="${var}_FILE"
	local def="${2:-}"
	if [ "${!var:-}" ] && [ "${!fileVar:-}" ]; then
		mysql_error "Both $var and $fileVar are set (but are exclusive)"
	fi
	local val="$def"
	if [ "${!var:-}" ]; then
		val="${!var}"
	elif [ "${!fileVar:-}" ]; then
		val="$(< "${!fileVar}")"
	fi
	export "$var"="$val"
	unset "$fileVar"
}
```

**Comment by martialblog** [comment]
Hi, yeah makes sense. I've had this on my mind for a while. 

You want to open a PR?

**Comment by martialblog** [comment]
Hi, the feature is in the latest Images.
