### ISSUE TITLE
Install and configure LDAP dependencies

### ISSUE THREAD

**Issue by SoerenBusse** [martialblog/docker-limesurvey#157]
**Description:**

The connection to an LDAP server with a valid certificate (StartTLS + LDAPS) fails with the message, that it cannot connect to the server. The same issue can be reproduced using the `ldapsearch` CLI command:

```
TLS: peer cert untrusted or revoked (0x42)
TLS: can't connect: (unknown error code).
```
To fix this, the following packages must be installed in the docker-container:
```
libldap-common libsasl2-modules
```

Additionally, it would be helpful to have an environment variable to optionally disable TLS certificate validation completely by writing the following to `/etc/ldap/ldap.conf`

```
TLS_REQCERT never
```

**Environment**:
Image: `docker.io/martialblog/limesurvey:6.1.5-230626-apache`

**Comment by martialblog** [comment]
Hey, tanks for the hint. Do you want to open a Pull Request for the packages?

Regarding the `/etc/ldap/ldap.conf` you could simply mount a file with the configuration into the container. I think that's the most flexible option.

**Comment by martialblog** [comment]
Hi, the packages are in the latest Images.
