### ISSUE TITLE
Just... Thanks

### ISSUE THREAD

**Issue by cavo789** [martialblog/docker-limesurvey#159]
Thanks Markus  for maintaining this repository.

I've used it months ago and now that I need to upgrade LimeSurvey instances hosted on our own server, first, I'm playing with different versions on my machine (5.x and 6x) to check how I'll make the upgrade from my old LS instances.

Thanks to you, it's really easy to install any prior versions of LS and play with, a.o.t., my SQL backup and check how newer versions are able to migrate my database structure f.i.

You're doing a great work; thanks!

**Comment by martialblog** [comment]
Hi, thanks for the feedback! It's very appreciated :heart:
