### ISSUE TITLE
GitHub Download URL changed

### ISSUE THREAD

**Issue by martialblog** [martialblog/docker-limesurvey#161]
The download link for the tarball changed. Has now `/refs/tags` in the URL

`https://github.com/LimeSurvey/LimeSurvey/archive/refs/tags/6.2.5+230828.tar.gz`

**Comment by edgarrmondragon** [comment]
Was this fixed by https://github.com/martialblog/docker-limesurvey/pull/162?

**Comment by martialblog** [comment]
Yes. But there were/are still some issues with the build. I think GitHub had some operational issues

**Comment by martialblog** [comment]
Latest builds are running again.
