### ISSUE TITLE
Postgres Central Participant database error

### ISSUE THREAD

**Issue by FriedrichMueller** [martialblog/docker-limesurvey#17]
Docker-Compose with postgres starts limesurvey but brings 500 Internal Server error with sql error if a new user is added with menu 'Configuration' -> central participant database -> add new participant.
Whereas docker-compose with mysql works. Does the postgres installation need further configs?

**Comment by martialblog** [comment]
Hey, do you have an error message from the application or database?

**Comment by martialblog** [comment]
Is it: 

> CDbCommand failed to execute the SQL statement: SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: character varying = integer
> LINE 1: ...73b-0d74423e4fd9' AND (share_uid = 1 AND can_edit = 1) LIMIT...
> ^
> HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.
> 

I could recreate that.

**Comment by martialblog** [comment]
Doens't happend with MySQL... I think this might be a Bug in the Application. 

I'll check the LimeSurvey Bugtracker

**Comment by martialblog** [comment]
Opened an issue in the LimeSurvey Bugtracker

https://bugs.limesurvey.org/view.php?id=15005

**Comment by FriedrichMueller** [comment]
Yep had the same error message in the application. Thx for report it it to limesurvey. I also solved it by using MYSQL which works errorless.

**Comment by martialblog** [comment]
They've fixed it: https://github.com/LimeSurvey/LimeSurvey/commit/6c6f350774974ce6b6bab514c50d54cbded78598

**Comment by martialblog** [comment]
I'm waiting for a new release, then I'll create the images and close this issue

**Comment by FriedrichMueller** [comment]
Perfect!-Thank you very much

**Comment by martialblog** [comment]
A new version was just released: https://github.com/martialblog/docker-limesurvey/releases/tag/3.17.7%2B190627

Cheers, Markus
