### ISSUE TITLE
Old Limesurvey version in latest

### ISSUE THREAD

**Issue by drdiscipulus** [martialblog/docker-limesurvey#170]
Really just a minor issue but I noticed that the current latest version bundles Limesurvey 6.2.5 instead of 6.2.9 - noticed it today when I wanted to upgrade from 6.2.7 to 6.2.9.

**Comment by martialblog** [comment]
Hi, which Image are you using? I just pulled and ran this one, and it's version 6.2.11

```
docker pull docker.io/martialblog/limesurvey:latest

latest: Pulling from martialblog/limesurvey
Digest: sha256:3344c7eb9675e17d196a23e76ecb761717b58bda829872055c095010272743d6

docker run -ti --rm --entrypoint bash docker.io/martialblog/limesurvey:latest

grep versionnumber application/config/version.php
$config['versionnumber'] = '6.2.11';
```

**Comment by drdiscipulus** [comment]
Hi, I am just using "image: martialblog/limesurvey:latest" to get the latest version 6 Apache image. Yesterday, however, instead of getting the expected version 6.2.9, I ended up with 6.2.5 - checked it on DockerHub and the latest tag showed 6.2.5 in the Docker File instead of 6.2.9. Everything is fine again with your 6.2.11 update - thanks!

**Comment by martialblog** [comment]
Ok good to know. We had some issues in the past with the automated builds... so I was worried for a second

**Comment by martialblog** [comment]
I'm closing this. 

Let me know if you run into any other issues. 

Thanks
