### ISSUE TITLE
Add additional check for $ENCRYPT_SECRET_BOX_KEY to the entrypoint-security.php-creation

### ISSUE THREAD

**Issue by wuarmin** [martialblog/docker-limesurvey#173]
Hey,

I think the env variable `$ENCRYPT_KEYPAIR` is not used at newer versions. So we should add a check for the presence of `$ENCRYPT_SECRET_BOX_KEY` to decide if the `security.php` file should be created. WDYT?

https://github.com/martialblog/docker-limesurvey/blob/7e73bf52238f9ba219d8c94bb52d1ad8ec95724e/6.0/apache/entrypoint.sh#L156

```sh
if [ -n "$ENCRYPT_KEYPAIR" ] || [ -n "$ENCRYPT_SECRET_BOX_KEY" ]; then
```

best regards

**Comment by martialblog** [comment]
Hi, 

you mean newer versions of LimeSurvey? Yes if the current LS version doesn't use this anymore, we can update the condition for the `security.php`. 

Do you want to open a PR? 

Thanks for noticing

**Comment by wuarmin** [comment]
Hello @martialblog,

> you mean newer versions of LimeSurvey?
Yes I mean versions >=5. We use version 6 and have to provide a dummy `$ENCRYPT_KEYPAIR` to make the composing work. 
I created a #174 

best regards

**Comment by martialblog** [comment]
Merged and I just added the new LS tags, so the Images will be updated shortly.

Thannks!
