### ISSUE TITLE
New Images for Release 6.3.1+231023?

### ISSUE THREAD

**Issue by KornKalle** [martialblog/docker-limesurvey#176]
Hey,

We are currently affected by this bug: https://bugs.limesurvey.org/view.php?id=19180 when using the latest docker image.
It got fixed in 6.3.0-231016-apache.

Would you mind trigger a new build for this release?

Kind Regards

**Comment by martialblog** [comment]
Hi, that Image should be present: https://hub.docker.com/layers/martialblog/limesurvey/6.3.0-231016-apache/images/sha256-d3a2a71e30e4ff1d585835dbd279db91e1c4a323611ef5c18be7149a680e9900?context=explore

**Comment by martialblog** [comment]
As for 6.3.1+231023, I work with the LS Tags on GitHub. As soon as they release this version the Images will be up.

**Comment by martialblog** [comment]
Hi, just pushed the new tags. The new images are on their way
