### ISSUE TITLE
SQL: SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist:

### ISSUE THREAD

**Issue by NexusEFR** [martialblog/docker-limesurvey#187]
New error in last version. When you want preview survey,etc..

SQL: SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: text <> integer
LINE 1: ...AND parent_qid=0 AND((attribute='hidden' AND value!=1 )OR at...
^
HINT: No operator matches the given name and argument types. You might need to add explicit type casts.

More info here..

https://bugs.limesurvey.org/view.php?id=19651

Fix in New docker release?

**Comment by edgarrmondragon** [comment]
The commit that fixed that error will be included in the 6.5.17 release, it just hasn't been tagged yet so there's nothing to do for this repo at the moment.

https://github.com/LimeSurvey/LimeSurvey/commit/f8d89cd5b46b5050fd87a974661f8705978d15fe.

**Comment by martialblog** [comment]
Just pushed the new version: https://github.com/martialblog/docker-limesurvey/commit/fc2764c55151ae4cc660e700d84b075eb6552437

Images are on their way.

@edgarrmondragon Thanks for the hint.
