### ISSUE TITLE
Internal Server error when loading Simple Statistics

### ISSUE THREAD

**Issue by TubYoub** [martialblog/docker-limesurvey#189]
Hi i get an Internel Server Error 500 when i try to load the Simple Statistsics.
I use the newest Image and this is the error i get displayed:
500: Interner Serverfehler - CDbCommand failed to execute the SQL statement: SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: ` character varying
LINE 1: ... FROM "lime_questions" "t" WHERE sid = 411374 and `type` = '...
^
HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.

**Comment by martialblog** [comment]
Hi, this reads like an application error. 

I think it's this: https://bugs.limesurvey.org/view.php?id=19711 

Seems they already have a fix but not sure it it's released yet.

**Comment by TubYoub** [comment]
sadly its not fixed but ty anyay
https://github.com/LimeSurvey/LimeSurvey/pull/3945

**Comment by edgarrmondragon** [comment]
> sadly its not fixed but ty anyay [LimeSurvey/LimeSurvey#3945](https://github.com/LimeSurvey/LimeSurvey/pull/3945)

I think it's fixed by https://github.com/LimeSurvey/LimeSurvey/commit/329670552190da242afb8d87f699d797179e6e1f, included in [6.6.3+240909](https://github.com/LimeSurvey/LimeSurvey/releases/tag/6.6.3%2B240909). Just a matter of building a Docker tag for that.

**Comment by martialblog** [comment]
6.6.3+240909 Images are up, should fix the issue.
