### ISSUE TITLE
LimeSurvey starts but doesn't work properly

### ISSUE THREAD

**Issue by VolodymyrBiryuk** [martialblog/docker-limesurvey#19]
Database and tables are created but the LimeSurvey page shows this:
![Screenshot 2019-07-16 at 11 13 34](https://user-images.githubusercontent.com/19716910/61282405-8e526c00-a7bb-11e9-9e78-8ec34360b6b6.png)

**Comment by jacksgt** [comment]
Hi there! It seems like LimeSurvey is working just fine! :-)

If you are looking for the admin backend, you need to navigate to http://YOUR.URL/index.php/admin

**Comment by VolodymyrBiryuk** [comment]
Oh boy, the embarrassment :) Thank you.

**Comment by jacksgt** [comment]
Haha, no worries. I also find it a bit confusing each time.

**Comment by martialblog** [comment]
:cat:

**Comment by martialblog** [comment]
I included the URLs the README  https://github.com/martialblog/docker-limesurvey/commit/02e2c9dc3a0400c85637d664cc935e3056c1b7c6
