### ISSUE TITLE
Upgrade postgres for ARM

### ISSUE THREAD

**Issue by xeruf** [martialblog/docker-limesurvey#197]
https://github.com/martialblog/docker-limesurvey/issues/138 not working with default compose because of old mysql:
```sh
[+] Running 0/1
 ⠴ lime-db Pulling                                                                                                                     3.5s 
no matching manifest for linux/arm64/v8 in the manifest list entries
```
Switched to postgres seems to makt it work, any reason why it specifies the woefully outdated version 10? Testing version 17 now.

**Comment by martialblog** [comment]
Thanks for the PR. https://github.com/martialblog/docker-limesurvey/pull/199

I'm closing this for now
