### ISSUE TITLE
Can't insert image (picture) in limesurvey

### ISSUE THREAD

**Issue by nichtleiter** [martialblog/docker-limesurvey#20]
Trying to insert an image via the limesurvey text editor fails.

After clicking 'Image' > 'Browse Server' limesurvey tells me:

```
Cannot find any of the supported PHP image extensions!
```

Although gd was successfully compiled during the building process of the docker image.

I wouldn't be surprised if i'm not alone with this issue.

Best regards

**Comment by martialblog** [comment]
Hi, thanks for the hint. I'll have a look at it

**Comment by martialblog** [comment]
@nichtleiter I think gd wasn't configured properly. Can you check out these changes: https://github.com/martialblog/docker-limesurvey/tree/fix-image-lib

**Comment by martialblog** [comment]
There's also an issue when the upload folder is not owned by the webserver user (e.g www-data). I'm looking into a solution.

**Comment by martialblog** [comment]
So there's no magic solution here... one solution would be to make the entrypoint set the correct owner everytime the container starts, or the admin has to set the correct permissions for the mounted directory.

**Comment by martialblog** [comment]
The example volumes in the docker-compose files also were wrong. I fixed the examples here: https://github.com/martialblog/docker-limesurvey/commit/051a22eb41b2041fa03ff13f338b8bf2e436b3ec

This should fix all the issues.

**Comment by nichtleiter** [comment]
Thanks for looking into it!

Now everything works as expected...
