### ISSUE TITLE
Permission error modifying theme files

### ISSUE THREAD

**Issue by jeresiv** [martialblog/docker-limesurvey#25]
Theme editor: bootswatch_CAN_bil
Viewing file '/var/www/html/themes/survey/vanilla/views/layout_global.twig'
×You can't save changes because the theme directory is not writable.

**Comment by martialblog** [comment]
Hi, how did you start the Container? I just tried editing/creating themes using the docker-compose.yml provided and that worked with no isses

`
limesurvey_1  | 172.21.0.1 - - [08/Mar/2020:09:01:45 +0000] "POST /index.php/admin/themes/sa/templatesavechanges HTTP/1.1" 302 481 "http://localhost:8080/index.php/admin/themes/sa/view/templatename/extends_fruity" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"`

**Comment by jeresiv** [comment]
I used the docker create command and the 4.1.6 apache container, this is for a test environment so I've left a lot of defaults alone.
docker create --name limesurvey \
-p 8080:80 \
-e DB_TYPE=pgsql \
-e DB_HOST=postgres \
-e DB_NAME=limesurvey \
-e DB_PASSWORD=password \
-e ADMIN_PASSWORD=admin \
martialblog/limesurvey:4.1.6_200220-apache

and then docker start limesurvey

**Comment by martialblog** [comment]
Hi, I can't seem to recreate this issue here :thinking:  

Can you try the docker-compose files for testing and give me some more feedback?

Regards, Markus

**Comment by martialblog** [comment]
Closed due to inactivity.
