### ISSUE TITLE
Docker hub tags

### ISSUE THREAD

**Issue by cdalexndr** [martialblog/docker-limesurvey#26]
The following `latest` tags would be helpful:

- latest-fpm
- latest-fpm-alpine
- latest-apache

So instead of using the complicated tag `4.1.9_200310-fpm-alpine`, we would use `latest-fpm-alpine`.

**Comment by martialblog** [comment]
Hi, personally I'm not a fan of the "latest" tags. There are many reasons why, see also https://vsupalov.com/docker-latest-tag/

Mainly it's you newer know what you're pulling. Example would be a major version change that requires you to do something or prepare.

**Comment by jacksgt** [comment]
I agree with @martialblog that it's somewhat dangerous to use latest tags (e.g. imagine you automatically upgraded from 3.0 to 4.0, both of which are present in this repository) and I personally also advise against it.

However, I also feel that for getting started it provides a very nice entry point. It also has the benefit that your environment always stays somewhat up-to-date.

Maybe we can find a middle ground here (also considering the maintenance overhead): use a similar approach to official DockerHub images and provide different tiers: https://github.com/docker-library/docs/blob/master/php/README.md#supported-tags-and-respective-dockerfile-links

E.g. (same for 3.x):

* 4-fpm
* 4-fpm-alpine
* 4-apache

These tags are then "rolling" with the newer releases.

But I'm not sure how easy this is to set up the automatic DockerHub builds.

**Comment by cdalexndr** [comment]
Also, is there a `stable` version? My experience with the latest versions is buggy.

**Comment by martialblog** [comment]
@cdalexndr What do you mean by buggy? If it is the application, they recently switched from version 3 to 4, with a lot of changes.

**Comment by cdalexndr** [comment]
I encountered some bugs while creating questions that makes it unusable, and I'm wondering if there is a baseline stable version that I can use until the bugs are resolved. 
I've reported them on their bug platform.

**Comment by martialblog** [comment]
I added some more automated Tags to the build.

Now we have:
- 4-fpm
- 4-fpm-alpine
- 4-apache

@jacksgt here's how you can do that just FYI. 

![Screenshot from 2020-03-23 09-36-49](https://user-images.githubusercontent.com/7090372/77298128-b0a56d80-6cea-11ea-9105-e65ba08729df.png)

**Comment by martialblog** [comment]
Auto-tags are in place and manual tags have been pushed. @cdalexndr thanks for the issue :+1:
