### ISSUE TITLE
Admin env variables have no effect after initial configuration

### ISSUE THREAD

**Issue by cdalexndr** [martialblog/docker-limesurvey#27]
Changing the admin env variables has no effect after initial configuration.
For example, changing `ADMIN_PASSWORD` doesn't update the admin's password.

You should either add a notice in the documentation stating they are valid only for initial configuration, or add a mechanism that updates the credentials.

**Comment by martialblog** [comment]
Thanks for the notice, I'll have a look at it

**Comment by jacksgt** [comment]
What is stated in this issue is definitely true, but it's also mentioned in the README (in the section just before "Environment Variables"):

> Limesurvey Configuration
> The entrypoint will create a new config.php if none is provided and run the LimeSurvey command line interface for installation.

**Comment by martialblog** [comment]
When creating the Image, I figured that once the config.php is in place it would be managed by something else: Either the user via the webinterface or some configuration management (i.e Puppet).

I'm gonna have a look at official Docker Images to get some idea on how to handle this.

**Comment by martialblog** [comment]
So many official Docker images I looked at don't have mechanisms in their entrypoint to change stuff in the database once initialized. I personally don't think it's a good idea to mess with the database bypassing the application.

I will update the README to be a bit more verbose about that.

**Comment by martialblog** [comment]
Readme was updated

**Comment by cdalexndr** [comment]
The `Environment Variables` table should also be changed from
`ADMIN_USER | LimeSurvey Admin User` to
`ADMIN_USER | Initial LimeSurvey Admin User`
Same for rest of admin env vars.

**Comment by martialblog** [comment]
Done
