### ISSUE TITLE
Question: did you encountered blank error on changing answer?

### ISSUE THREAD

**Issue by cdalexndr** [martialblog/docker-limesurvey#28]
https://bugs.limesurvey.org/view.php?id=16008

**Comment by martialblog** [comment]
Hi, I did manage to recreate this error as you described.

If you set the debug to 2, you can actually see the error message. I think this is an application bug I'll update the issue in the LimeSurvey Bugtracker

![error](https://user-images.githubusercontent.com/7090372/77740269-3c810780-7013-11ea-83b2-537e6d90a2c1.png)

**Comment by martialblog** [comment]
@cdalexndr I couldn't update the issue, can you reopen it? Then I can give some details

**Comment by martialblog** [comment]
Hint: You dont even have to change the question type. Just add a new  "Bootstrap buttons Type: L", save an answer and then try to change it.

**Comment by martialblog** [comment]
I just tested it with MySQL and there don't seems to be an issue. Just Postgres it seems

**Comment by cdalexndr** [comment]
Can you add a note to the issue? Maybe some admin will open the issue.
I cannot do any changes to the issue besides adding a note. Only admins can do that.

**Comment by martialblog** [comment]
No, I tried but it said "Read Only". As the issuer, you should be able to reopen it though

**Comment by cdalexndr** [comment]
I cannot reopen it. I've encountered multiple issues using their bug tracker (Mantis). I've reported them and suggested to move to GitHub but they refused.
You can open a new issue and say it's a duplicate of my issue...

**Comment by olleharstedt** [comment]
Hi ho. To motivate us to fix this issue, you must either: 1) Subscribe to any of our packages (they all include technical support); or 2) Replicate the bug outside this docker container. You're always welcome to make a PR with a fix to our github repository. The company LimeSurvey GmbH has no relation to this docker container at all.

**Comment by martialblog** [comment]
@olleharstedt Hi, we're just trying to help improve your software, no need for the hostility.

Anyways, I did manage to recreate this in a Vagrant box with a fresh LS 4.1.12+200324 installation. 

System:
```
root@server:~# lspci | grep VirtualBox
00:02.0 VGA compatible controller: InnoTek Systemberatung GmbH VirtualBox Graphics Adapter
00:04.0 System peripheral: InnoTek Systemberatung GmbH VirtualBox Guest Service

root@server:~# apache2 -V
Server version: Apache/2.4.38 (Debian)
Server built:   2019-10-15T19:53:42
Server's Module Magic Number: 20120211:84
Server loaded:  APR 1.6.5, APR-UTIL 1.6.1
Compiled using: APR 1.6.5, APR-UTIL 1.6.1

root@server:~# psql --version
psql (PostgreSQL) 11.7 (Debian 11.7-0+deb10u1)

root@server:~# php --version
PHP 7.3.14-1~deb10u1 (cli) (built: Feb 16 2020 15:07:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.14, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.14-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
```

Here's the error from the application log:
```
2020/03/28 04:13:01 [warning] [application] Failed to set unsafe attribute "aid" of "Answer".
2020/03/28 04:13:01 [warning] [application] Failed to set unsafe attribute "en" of "Answer".
2020/03/28 04:13:01 [error] [exception.LSJsonException.500] LSJsonException: Question has been stored, but an error happened: 
 in /var/www/html/application/controllers/admin/questionedit.php:297
Stack trace:
#0 [internal function]: questionedit->saveQuestionData(762155)
#1 /var/www/html/framework/web/actions/CAction.php(109): ReflectionMethod->invokeArgs(Object(questionedit), Array)
#2 /var/www/html/application/core/Survey_Common_Action.php(86): CAction->runWithParamsInternal(Object(questionedit), Object(ReflectionMethod), Array)
#3 /var/www/html/framework/web/CController.php(308): Survey_Common_Action->runWithParams(Array)
#4 /var/www/html/framework/web/CController.php(286): CController->runAction(Object(questionedit))
#5 /var/www/html/framework/web/CController.php(265): CController->runActionWithFilters(Object(questionedit), Array)
#6 /var/www/html/application/controllers/AdminController.php(172): CController->run('questioneditor')
#7 /var/www/html/framework/web/CWebApplication.php(282): AdminController->run('questioneditor')
#8 /var/www/html/framework/web/CWebApplication.php(141): CWebApplication->runController('admin/questione...')
#9 /var/www/html/framework/base/CApplication.php(185): CWebApplication->processRequest()
#10 /var/www/html/index.php(182): CApplication->run()
#11 {main}
REQUEST_URI=/index.php/admin/questioneditor/sa/saveQuestionData/gid/1/sid/762155
HTTP_REFERER=http://localhost:8888/index.php/admin/questioneditor/sa/view/surveyid/762155/gid/1/qid/1
---
2020/03/28 04:13:02 [warning] [application] Failed to set unsafe attribute "code" of "QuestionType".
2020/03/28 04:13:02 [warning] [application] Failed to set unsafe attribute "description" of "QuestionType".
2020/03/28 04:13:02 [warning] [application] Failed to set unsafe attribute "group" of "QuestionType".
2020/03/28 04:13:02 [warning] [application] Failed to set unsafe attribute "subquestions" of "QuestionType".
2020/03/28 04:13:02 [warning] [application] Failed to set unsafe attribute "hasdefaultvalues" of "QuestionType".
2020/03/28 04:13:02 [warning] [application] Failed to set unsafe attribute "assessable" of "QuestionType".
2020/03/28 04:13:02 [warning] [application] Failed to set unsafe attribute "answerscales" of "QuestionType".
2020/03/28 04:13:02 [warning] [application] Failed to set unsafe attribute "class" of "QuestionType".

```

Attached is also a full trace log.

[limesurvey-postgres-error.log](https://github.com/martialblog/docker-limesurvey/files/4396613/limesurvey-postgres-error.log)

I'm not a PHP Dev myself, is there anyway we can get you more info?

**Comment by olleharstedt** [comment]
Did the error show up in the browser? Popup or similar.

**Comment by martialblog** [comment]
If the debugging is disabled (level 0), then you just get a blank error popup as @cdalexndr described here https://bugs.limesurvey.org/view.php?id=16008

If the debug is on, then you get the error popup I posted https://github.com/martialblog/docker-limesurvey/issues/28#issuecomment-604894567

**Comment by PSCC9t** [comment]
For me this error occurs when my question codes are too long. 
However, this only seems to be a problem when using the List Radio Type L.

**Comment by martialblog** [comment]
The error bug is now fixed. Tested it with 3.25.15+210223 and 4.4.10+210222
