### ISSUE TITLE
php-fpm setup has incomplete Nginx configuration

### ISSUE THREAD

**Issue by jsfan** [martialblog/docker-limesurvey#30]
The Nginx configuration as included for php-fpm and Nginx does not seem to work as is. Some assets are served with wrong MIME types. Those assets may then be rejected by the browser rendering the web application unusable.

To fix, the Nginx configuration needs to include the line

    include /etc/nginx/mime.types;

**Comment by martialblog** [comment]
Hi, thanks for the hint. Will you open a PR or should I do it?

**Comment by martialblog** [comment]
Fixed with https://github.com/martialblog/docker-limesurvey/commit/3639cc38e843a805a5fc820ec8569f3be73901e6
