### ISSUE TITLE
Encounter error when executing docker-compose up

### ISSUE THREAD

**Issue by KyonCN** [martialblog/docker-limesurvey#32]
```
lime-db_1     | 2020-05-05T12:23:05.119759Z 0 [Note] mysqld: ready for connections.
lime-db_1     | Version: '5.7.30'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
limesurvey_1  | Info: Waiting for database connection...
limesurvey_1  | docker-limesurvey_lime-db_1: forward host lookup failed: Unknown host
limesurvey_1  | docker-limesurvey_lime-db_1: forward host lookup failed: Unknown host
.....
```
The  following errors are all the same failure

**Comment by jacksgt** [comment]
Could you give a few more details please?
Which version of the image are running, which environment variables are you setting?

Ideally, paste the docker command you're running or the docker-compose.yml file here.

**Comment by martialblog** [comment]
The current  compose file has `"DB_HOST=docker-limesurvey_lime-db_1" in it`, which can probably be changed to just `limesurvey` since Docker should take care of the name resolution

**Comment by KyonCN** [comment]
I used the docker-compose.yml in the repo.
And I changed the `"DB_HOST=docker-limesurvey_lime-db_1" ` to` "DB_HOST=dockerlimesurvey_lime-db_1" ` , it works well now.
