### ISSUE TITLE
Encryption keys should be stored

### ISSUE THREAD

**Issue by galaxyoyo** [martialblog/docker-limesurvey#33]
The file `/var/www/html/application/config.security.php` contains 2 encryption keys that should be properly volumed, otherwise each encrypted data would be lost after a reboot.

**Comment by martialblog** [comment]
Hi, this for the hint. Gotta think of something, since the keys get generated on the first start... 

Cheers

**Comment by martialblog** [comment]
Ok, so from I gathered the keys can also be in the config.php

> You can move this settings in config.php if you want or leave in security.php.
Source: https://manual.limesurvey.org/Optional_settings#Encryption_settings_.28New_in_4.0.0_.29

I'll first add some ENV variables to provide the keys to the config.php. 

Maybe I can figure out a way to leverage the key generation from the app, so that you automatically get some keys in the volumed config.php... that be cool

**Comment by martialblog** [comment]
Ok, so I figured this was a good time to refactor the entrypoint. I didn't want to be too opinionated about what the user should do...

The options in the new entrypoint would be: 
1. You can provide the security.php directly
1. You can provide encryption keys and it creates a security.php 
1. You provide nothing and get a non-persistent security.php, which you have to backup somehow (+ A warning in the stderr)

:thinking: Should the entrypoint exit with an error when you get non-persistent keys? @jacksgt What do you think?

https://github.com/martialblog/docker-limesurvey/tree/refactor-entrypoint

**Comment by jacksgt** [comment]
I think you did the right thing by making it optional. Don't exit if the keys are not given, just print a warning.

BTW: Is this data encryption in LimeSurvey 4 optional or mandatory?

**Comment by martialblog** [comment]
Quote:

>  If you don't want to use data encryption, you have to disable encryption in attribute settings.

**Comment by martialblog** [comment]
@galaxyoyo Hi, the branch with the keys is ready to be tested. Everything should work, but I still wanna do some checks tomorrow.

**Comment by galaxyoyo** [comment]
Thank you :)
