### ISSUE TITLE
Interest in a Docker Compose Example with Traefik, Let's Encrypt Automatic SSL

### ISSUE THREAD

**Issue by muniter** [martialblog/docker-limesurvey#37]
Hey, yesterday I used the example docker compose from the repo, did some modifications and set it up with traefik as reverse proxy and automatic SSL renewal, for simple `docker-compose up -d` deployment. If you're interested in having It in the repo, I'll be happy to clean it up, create some instructions and send a PR

**Comment by martialblog** [comment]
Hi, yeah sure. Open the PR and I'll have a look at it. 

You can place it next to the other docker-compose examples.

**Comment by martialblog** [comment]
Hi, I'm closing this. If you still want to provide an example, simply open a PR.
