### ISSUE TITLE
LS 3.23.2 has a critical bug

### ISSUE THREAD

**Issue by DeveloperChris** [martialblog/docker-limesurvey#39]
I installed your docker file today but it crashed due to this bug 
https://bugs.limesurvey.org/view.php?id=16488

version 3.23.3 was just released.

Thanks for your outstanding work :+1:

**Comment by martialblog** [comment]
Hi, thanks for the hint. I use the GitHub Tags to compile new versions, seems as it the new 3.23.3+200909  is not yet there...

**Comment by martialblog** [comment]
Tried to contact the devs https://bugs.limesurvey.org/view.php?id=16654

**Comment by DeveloperChris** [comment]
I patched this in the running container from the changes made here. 

https://github.com/LimeSurvey/LimeSurvey/commit/27d16225077ca3c449bd15fa77014f4dd4c71353

**Comment by martialblog** [comment]
I'd love to fix this, but I'm not sure if I should hack a patch :thinking: Hopefully they'll upload a release soon

**Comment by martialblog** [comment]
Finally :fireworks: https://github.com/martialblog/docker-limesurvey/releases/tag/3.23.3%2B200909
