### ISSUE TITLE
There is an tcpdf error, when trying to view response details as queXML PDF

### ISSUE THREAD

**Issue by neuronick** [martialblog/docker-limesurvey#45]
There is an tcpdf error, when trying to view response details as queXML PDF:

![image](https://user-images.githubusercontent.com/838476/100383400-d1faee00-301d-11eb-86fc-7dbf2d42e611.png)

![image](https://user-images.githubusercontent.com/838476/100383108-205bbd00-301d-11eb-81ef-2ba92fc9b817.png)

See the solution here:
https://sourceforge.net/p/tcpdf/bugs/1147/

TCPDF probably need to be upgraded or patched.

I am using this image: martialblog/limesurvey:3.25.0_201117-apache

But the same version of tcpdf is used on the latest 3.x / 4.x on limesurvey/limesurvey

**Comment by martialblog** [comment]
Hey, thanks for the hint. I'll have a look at it. 

Cheers,
Markus

**Comment by martialblog** [comment]
Hi, 

I tried to recreate the error, but everything worked as excepted (tested with Version 4.3.27, Version 3.25.0, fresh builds, docker-compose.yml)

Can you provide some more details on your environment? And how to recreate the issue?

Cheers, 
Markus

**Comment by neuronick** [comment]
Hi,

In order to recreate, you have to setup debug level to 2.

Greetings,
Nikita

**Comment by martialblog** [comment]
Ok, so I did manage to recreate that error... but it's definitely application related. I opened an issue in the LS BugTracker to let the devs know: https://bugs.limesurvey.org/view.php?id=16872

**Comment by martialblog** [comment]
@neuronick Looks like you weren't the first with this issue:

https://github.com/LimeSurvey/LimeSurvey/commit/bddef7c8dc926cbbb5b56217131ea8a471b6fc7f

Will be fixed in the 4.3.29 Release

**Comment by martialblog** [comment]
Should be fixed with https://github.com/martialblog/docker-limesurvey/commit/0f7d4ef58f2cd89ece06851ca05409fde0684807
