### ISSUE TITLE
New build number of LS not reflected in Admin Panel - How to upgrade version?

### ISSUE THREAD

**Issue by MarkErik** [martialblog/docker-limesurvey#47]
I don't think this is necessarily an issue with this project, but I was hoping that there could be instructions/recommendations how to upgrade the LS installation.

Steps I do:
1. Pull the latest Dockerfile (when new build number updated).
2. Run 'docker-compose build'
3. Start all the containers.

The result is that the build number in the Admin panel is still showing the old build number from when I first built the container.

I am guessing it is because I don't know if:
- Database needs updating somehow?
- The docker volume for LimeSurvey is still the old one?

My current work-around is to delete my database and docker volume - then recreate everything.

If there is a recommended way to be able to upgrade LS, would it make sense to include it in the Readme?

**Comment by martialblog** [comment]
Hey, could it be that docker-compose used the already existing container? So far I never had issues with an update.

**Comment by MarkErik** [comment]
With the new release, I wanted to try out the process again.

The starting point:
<img width="613" alt="Screenshot 2020-12-09 at 8 36 00 AM" src="https://user-images.githubusercontent.com/23254168/101640834-021f9500-39ff-11eb-9e44-0a2131c15619.png">

Then I stopped and removed all containers.

Then I ran docker-compose build --no-cache

Here's the relevant output:
```
Step 5/14 : RUN curl -sSL "https://github.com/LimeSurvey/LimeSurvey/archive/${version}.tar.gz" --output /tmp/limesurvey.tar.gz
 ---> Running in b205cb7a5218
Removing intermediate container b205cb7a5218
 ---> 5b82f77de6f3
Step 6/14 : RUN set -ex;         tar xzvf "/tmp/limesurvey.tar.gz" --strip-components=1 -C /var/www/html/ &&                 rm -rf "/tmp/limesurvey.tar.gz"         /var/www/html/docs         /var/www/html/tests         /var/www/html/*.md &&         mkdir -p /var/limesurvey/runtime
 ---> Running in a0804b17b9d8
+ tar xzvf /tmp/limesurvey.tar.gz '--strip-components=1' -C /var/www/html/
LimeSurvey-3.25.2-201131/.bowerrc
LimeSurvey-3.25.2-201131/.editorconfig
```

So it did grab the new version, but in the dashboard it was still showing the old version number.
Note that I didn't remove the DB files or the lime volume - I wanted to see whether just rebuilding the lime survey container would be sufficient.

**Comment by MarkErik** [comment]
Update: If I  run "docker volume rm limesurvey-lime" then when I start the containers the new version is used - BUT - appears that a few problems creep in, for example if I have an extended theme, it still shows up, because the database was aware of it, but the actual elements were lost - which makes sense since they are stored in the volume that I just deleted.

I will now look at what folders I can mount from my computer into the container that need to be persisted so that I can remove the volume each time.

**Comment by martialblog** [comment]
I'm closing this for now. Can be re-opened if there's still an issue
