### ISSUE TITLE
The status icon is not change when survey is started or expired

### ISSUE THREAD

**Issue by danielchan-bss** [martialblog/docker-limesurvey#50]
Hi all. I have faced a problem when I am using the access control settings. 
In my case, I have set the Start date/time to "12.03.2021 16:14" and activated the survey. 
The survey is cannot access before "12.03.2021 16:14" and can access on or after "12.03.2021 16:14" normally. 
However, the status icon is still in "Activated but not yet started" after "12.03.2021 16:14". 
I have checked it is related to the timezone problem as "12.03.2021 16:14" is in HKT. 

LimeSurvey version: 4.3.23
Are there any solution to solve this issue? Thanks!

![image](https://user-images.githubusercontent.com/80511740/110914486-6715be80-8351-11eb-8827-1d80c8a52285.png)
![image](https://user-images.githubusercontent.com/80511740/110914634-95939980-8351-11eb-898f-f64e0a6a8d9c.png)

**Comment by martialblog** [comment]
Hi, have you tried a newer version (4.4.11+210301)? This sounds like a problem with the application.

**Comment by danielchan-bss** [comment]
I pull the image "martialblog/limesurvey:4-apache" but it is still same issue in version 4.4.12.

**Comment by danielchan-bss** [comment]
Found that the reason is the timezone of php in container is UTC. 
After changed the timezone of php.ini file in container, this works.

**Comment by pathros** [comment]
@danielchan-bss Could you please tell where you found the `php.ini` file and how you restarted the container to apply the changes?

Inside the limesurvey php-fpm container at `/usr/local/etc/php` I see there're two php.inis: 
* `php.ini-development`
* `php.ini-production`

Did you edit the production one? In that case, how do you tell the container which .ini you want to use?
