### ISSUE TITLE
Captcha not working

### ISSUE THREAD

**Issue by rafaelmr2** [martialblog/docker-limesurvey#54]
Hi,

I'm enabling captcha and doesn't show anything. What's can happening?

Thanks.

**Comment by martialblog** [comment]
Hello, are you using the latest version? There was an issue with the graphics libs I fixed just recently, https://github.com/martialblog/docker-limesurvey/pull/52

Regards

**Comment by rafaelmr2** [comment]
Yes. I'm using the branch master, and it's updated.

**Comment by martialblog** [comment]
I just tested the CAPTCHA function with a survey, worked as expected. Can you give me some details on the issue and where it occurs?

**Comment by rafaelmr2** [comment]
In "Publication & access" I put "Use CAPTCHA for survey access: ON" and save. The survey works normally, but it shows any CAPTCHA.

I'm using fpm-alpine.

**Comment by martialblog** [comment]
Hello, I just tested the latest fpm-alpine version, everything seems to work as expected. Can you double check your settings and maybe enable the DEBUG=2 ? 

Cheers, Markus

**Comment by rafaelmr2** [comment]
I'm not tested for a long time. But it's working now on latest version (5.2.4). Thanks!

**Comment by FMABP** [comment]
Hi, I have the same problem. My version is Version 5.3.32 and the image is martialblog/limesurvey:latest

**Comment by FMABP** [comment]
> Hi, I have the same problem. My version is Version 5.3.32 and the image is martialblog/limesurvey:latest

In 5.4.0 version it's working, thank you
