### ISSUE TITLE
Upgrade using newer fpm image version

### ISSUE THREAD

**Issue by thegcat** [martialblog/docker-limesurvey#56]
This is a question that is as much about how docker works than how this image uses docker but I hope you will be able to clarify this point.

The `docker-compse.fpm`s use a named volume to share the LimeSurvey installation path `/var/www/html` between multiple containers. My understanding of volumes is that if the volume is empty it will be populated with what is in the path it is mounted to in the image, i.e. the first time you start the `docker-compose.fpm` the content from the LimeSurvey docker image's `/var/www/html` will be copied to the named volume. If the named volume already has content, as will be the case on subsequent starts of the `docker-compose.fpm`, the volume will be mounted over the content already existing in the image.

This has the effect that you will be effectively using the LimeSurvey version the named volume was first created with until you recreate that named volume for whatever reason, as the named volume will be populated the first time you start the `docker-compose.fpm` and will subsequently be mounted over and not be replaced with the docker image contents.

Is this a correct comprehension of how Docker works and how this pans out for this case with these images? If not what is the intended way to upgrade the LimeSurvey when using the fpm images?

**Comment by thegcat** [comment]
This question is somewhat related to #47 though the answer there does not clarify if and how using the fpm images and updating is intended.

**Comment by martialblog** [comment]
Hey, I gotta admit I work rarely with `docker-compose` besides testing. The docker-compose files in this repo are intended to be examples, not production ready code. 

LS can be updated by simply overwriting the existing files and running `console.php updatedb` when there are DB updates. But, as you describe, that might not work if there are already files in a volume... I'm happy to merge any details/updates you wanna add to the docker-compse.yml 

Cheers, Markus

**Comment by martialblog** [comment]
Might be unrelated, but I just saw this article on HackerNews: https://nickjanetakis.com/blog/best-practices-around-production-ready-web-apps-with-docker-compose

**Comment by martialblog** [comment]
Finally found some time to look at this. 

If you are using docker-compose to run the FPM Images, you need to stop the application and webserver Containers and delete the application volume:

```
$ docker volume ls
DRIVER    VOLUME NAME
local     docker-limesurvey_lime

$ docker volume rm docker-limesurvey_lime
```

Afterwards start the new application container and webserver, and you got the new version. I'll update the README

**Comment by thegcat** [comment]
That's also more or less what I understood would be necessary, but haven't gotten around to trying it 😅 And thus couldn't confirm if it takes care of the issue. I'll still report back after we have tried it out, thank you!

**Comment by thegcat** [comment]
Another question regarding the fpm images: doesn't `/var/www/html/upload/surveys` need to be accessible to the web server, and it seems odd to use a folder in `/tmp` on the host for this, as `/tmp` on the host is not persistent?

**Comment by jacksgt** [comment]
@thegcat Are you talking about this line?

https://github.com/martialblog/docker-limesurvey/blob/958ed57011972a8145b4dfc384317ee48a4a4571/docker-compose.fpm.yml#L8

**Comment by thegcat** [comment]
> @thegcat Are you talking about this line?
> 
> https://github.com/martialblog/docker-limesurvey/blob/958ed57011972a8145b4dfc384317ee48a4a4571/docker-compose.fpm.yml#L8

Yes.

**Comment by jacksgt** [comment]
@thegcat You are correct that this data should be mounted at a persistent location (not /tmp).
There is a slight misunderstanding here: as @martialblog alluded to earlier, the docker-compose files are intended to be quick how-tos, because they show in a comprehensive way how to the containers can be started -- but aren't necessarily made to be "production templates".
Therefore, they use a /tmp as a quick, throwaway mount point.

However, the README states the following (which kind of opposes this viewpoint):
> The easiest way to get a fully featured and functional setup is using a docker-compose file. Several examples are provided in the repository.

So we should either a) adjust the wording in the README, or b) adjust the mount path in docker-compose files:
```diff
- - /tmp/upload/surveys:/var/www/html/upload/surveys 
+ - /var/www/limesurvey/upload/surveys:/var/www/html/upload/surveys 
```

**Comment by thegcat** [comment]
Thanks. I can understand this being an example and thus using `tmp`, no harm in that. The second part of the question was whether it is necessary to have that mounted to the "web" Container too or if the web server doesn't handle anything there.

**Comment by martialblog** [comment]
I'll put a hint in the docker-compose examples.
