### ISSUE TITLE
Make showScriptName configurable

### ISSUE THREAD

**Issue by thegcat** [martialblog/docker-limesurvey#63]
We would like to not show the php file in the url, i.e. have `showScriptName` be `false`. Having this be configurable would be nice.

**Comment by martialblog** [comment]
Hey, I added a variable for the config, is there anything else required? I haven't had the time to read the documentation in detail.

**Comment by thegcat** [comment]
From what I can see Apache just needs `mod_rewrite` to be enabled and everything else should just work. For the `nginx` example configuration I think at least the `r=$uri` query parameter must be added to https://github.com/martialblog/docker-limesurvey/blob/master/examples/nginx.conf#L20. See the [Limesurvey FAQ entry](https://manual.limesurvey.org/General_FAQ#With_nginx_webserver) for reference. Using this whole example `nginx` config for your example `nginx` config would probably work too.

**Comment by martialblog** [comment]
The variable is in the new release. mod_rewrite was already enabled.

Let me know if there's anything else. Feel free to open a PR if there need to be changes.

All the best
Markus
