### ISSUE TITLE
Limesurvey 5 images on docker hub?

### ISSUE THREAD

**Issue by thegcat** [martialblog/docker-limesurvey#66]
Just checking if the lime survey 5 images will be made available on docker hub or if we should take care of building it ourselves? Thanks.

**Comment by martialblog** [comment]
Hey, there've been some Changes to the AutoBuild recently (https://www.docker.com/blog/changes-to-docker-hub-autobuilds/) and I'm looking for a way to build the Images somewhere. 

Any ideas are welcome.

I'll build and push newer images manually as soon as possible.

**Comment by martialblog** [comment]
I just pushed new Images.

**Comment by thegcat** [comment]
> I just pushed new Images.

thanks

**Comment by thegcat** [comment]
> Hey, there've been some Changes to the AutoBuild recently (https://www.docker.com/blog/changes-to-docker-hub-autobuilds/) and I'm looking for a way to build the Images somewhere.
> 
> Any ideas are welcome.

It should be possible using GitHub Actions, see https://docs.github.com/en/actions/guides/publishing-docker-images

**Comment by martialblog** [comment]
Yes, I also got the Travis CI build for testing the images running. I'm gonna look into it soon.

Cheers!

**Comment by jacksgt** [comment]
FYI: It's unclear how long Travis CI free plans will be around
https://daniel.haxx.se/blog/2021/06/14/bye-bye-travis-ci/

At least Github has Microsoft behind it for now.

**Comment by martialblog** [comment]
Hopefully not, but yeah it's a possibility. I fear it's just a matter of time until some crypto gang ruins the next free service.

**Comment by thegcat** [comment]
Thank you!
