### ISSUE TITLE
Add Variables to configure Caching

### ISSUE THREAD

**Issue by martialblog** [martialblog/docker-limesurvey#73]
We should add some variables to configure Caching. Especially when we want some autoscaling deployments. 

> LimeSurvey uses the Yii file cache by default, but it can be configured to use other cache engines. Possible other caches are:
> 
>     Memcached
>     Redis
>     WinCache
>     XCache

https://manual.limesurvey.org/Installation_-_LimeSurvey_CE

**Comment by arjunsriva-woven** [comment]
+1 this will be great!

**Comment by martialblog** [comment]
I looked into this and I don't think it's feasable to include specific config in the Dockerfile. 

It is way simpler to just mount an existing config.php file, the entrypoint.sh already can handle that.
