### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by JensHeinrich** [martialblog/docker-limesurvey#78]
Even though mentioned in the `CONTRIBUTING.md` there is no `run.sh` in the tests folder and there also is no `test` job in the `Makefile`

**Comment by martialblog** [comment]
Hi, 

yeah there has been some refactoring when we moved to GitHub Actions. The run.sh was just a little wrapper to run the containter-structure-tests locally.

I wanted to provide something more flexible but haven't had the time yet.

**Comment by martialblog** [comment]
I updated the CONTRIBUTING.md

All you gotta do is download the container-structure-test tool, build the image you want to test, and test it. Examples are provided. 

Thanks for the hint!
