### ISSUE TITLE
Feature Request : SMTP email configuration using environment variables

### ISSUE THREAD

**Issue by arjunbazinga** [martialblog/docker-limesurvey#83]
Hi! 

I was wondering if there were any plans to add configuring the smtp settings using the docker environment variables ?

Thank you for creating this!

Arjun

**Comment by martialblog** [comment]
Hey, is there an option in LS to do this via config files? As far as I know, the Mail config is set via the WebUI and stored in the DB... I could be wrong though.

If we can set it via variables, then we can add this for sure.

Cheers
Markus

**Comment by arjunbazinga** [comment]
Hey! Just checked, yup you're right, thanks, closing.

**Comment by martialblog** [comment]
@arjunbazinga They provide a `console.php` for doing operations from the terminal (such as installation), maybe you can ask the LimeSurvey Devs if they can extend this tool to also install SMTP settting.
