### ISSUE TITLE
Quota function cause internal server error

### ISSUE THREAD

**Issue by TonyWanBCT** [martialblog/docker-limesurvey#86]
After I apply quota function in a survey and active it, I get this error when I try to submit after answer the question:

Version 4.5.1

![未命名](https://user-images.githubusercontent.com/88649286/128669331-51e05175-35f8-4073-bd85-aec649a06659.png)

**Comment by martialblog** [comment]
Hey, can you provide some details on how you started the application (database, etc) and how to recreate the issue?

I assume this is an application issue and not a Container issue, but let's confirm that first.

**Comment by TonyWanBCT** [comment]
> Hey, can you provide some details on how you started the application (database, etc) and how to recreate the issue?
> 
> I assume this is an application issue and not a Container issue, but let's confirm that first.
here is my yml file
version: '3'
services:
  limesurvey:
    image: docker.io/martialblog/limesurvey:4.5.1_210420-apache
    restart: always
    environment:
      - DB_TYPE=pgsql
      - DB_PORT=5432
      - DB_HOST=limesurvey_db
      - DB_PASSWORD=*************
      - DB_NAME=limesurvey
      - DB_USERNAME=limesurvey
      - ADMIN_USER=admin
      - ADMIN_NAME=Admin
      - ADMIN_PASSWORD=*************
      - ADMIN_EMAIL=****************
      - TZ=Asia/Hong_Kong
    volumes:
      - /usr/local/limesurvey/containeradjust.sh    :/usr/local/bin/containeradjust.sh
      - /usr/local/limesurvey/upload                :/var/www/html/upload/surveys
      - /usr/local/limesurvey/config/ldap.php       :/var/www/html/application/config/ldap.php
      - /usr/local/limesurvey/SSL                   :/var/www/html/SSL
      - /usr/local/limesurvey/default-ssl.conf      :/usr/local/bin/default-ssl.conf
    ports:
      - 8080:80
      - 8443:443
    depends_on:
      - limesurvey_db
  limesurvey_db:
    image: docker.io/library/postgres:10
    restart: always
    environment:
      - POSTGRES_USER=limesurvey
      - POSTGRES_DB=limesurvey
      - POSTGRES_PASSWORD=*************
    volumes:
      - /usr/local/limesurvey/db:/var/lib/postgresql/data

**Comment by TonyWanBCT** [comment]
> Hey, can you provide some details on how you started the application (database, etc) and how to recreate the issue?
> 
> I assume this is an application issue and not a Container issue, but let's confirm that first.

I agree that should be an application issues, but I cannot find any related post in limesurvey official site. 
I wanna know is that anyone here have similar issue.

**Comment by martialblog** [comment]
You can try to increase the DEBUG Level and see if you can get details on the error

- DEBUG=2
- DEBUG_SQL=2

If it's a bug in the application we can open an issue in the LS bugtracker.

**Comment by martialblog** [comment]
@TonyWanBCT I just tried to recreate the issue with LS version 5.0.13-210804 but no success so far. 

Can you provide some more details on how to recreate the issue?

**Comment by martialblog** [comment]
I'm closing this due to missing feedback. If you can provide a way to recreate this issue, we can reopen.
