### ISSUE TITLE
Allow DB without table prefix

### ISSUE THREAD

**Issue by ctueck** [martialblog/docker-limesurvey#88]
If I see and notice correctly, the current entrypoint.sh scripts do not allow to unset DB_TABLE_PREFIX. When it is set to an empty string it always falls back to the default `lime_`.

(I am planning to migrate an existing Limesurvey installation to Docker, and our install has no prefix.)

**Comment by martialblog** [comment]
Hey, you can also provide an existing `config.php` then the entrypoint will skip all the initialization stuff. 

But yeah, makes sense to allow an empty prefix. 

Cheers
Markus

**Comment by martialblog** [comment]
@ctueck  Hi, I just pushed some code that should fix this. See PR, feel free to test it.
